version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads  # Persistent storage for uploads
      - ./models:/app/models    # Persistent storage for models
    environment:
      - FLASK_ENV=production
      - MODEL_DIR=/app/models
      - UPLOAD_FOLDER=/app/uploads
    restart: unless-stopped